# Generated by Django 4.2.13 on 2024-06-04 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChessProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.IntegerField()),
                ('k', models.IntegerField()),
                ('rq', models.IntegerField()),
                ('cq', models.IntegerField()),
                ('obstacles', models.TextField()),
                ('result', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
